sudo: false
language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '8'
- '10'
- '12'
jobs:
  include:
  - stage: install
    script: npm install
  - stage: validate
    script: npm run validate
  - stage: codecov
    node_js: '12'
    script: npx codecov
  - stage: release
    node_js: '12'
    deploy:
      provider: script
      script: npx semantic-release
      skip_cleanup: true
branches:
  only: master
