sudo: false
language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '8'
- '10'
- '12'
install: npm install
script: npm run validate
jobs:
  include:
  - stage: release
    node_js: '12'
    deploy:
      provider: script
      script: npx codecov && npx semantic-release
      skip_cleanup: true
branches:
  only: master
