sudo: false
language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '8'
- '10'
- '12'
script: echo "Running tests against $(node -v) ..."
install: npm install
jobs:
  include:
  - stage: validate
    script: npm run validate
  - stage: release
    script: echo "Deploying to npm..."
    node_js: '12'
    deploy:
      provider: script
      script: npx semantic-release
      skip_cleanup: true
branches:
  only: master
