sudo: false
language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '8'
- '10'
- '12'
install: npm install
jobs:
  include:
  - stage: test
    node_js: '12'
    script: npm run validate && npx codecov
  - stage: release
    node_js: '12'
    deploy:
      provider: script
      script: npx semantic-release
      skip_cleanup: true
branches:
  only: master
